version: '2'
services:
  web:
    build: .
    ports:
      - "8088:5000"
    volumes:
      - /home/rick/opt/pets-api:/home/rick/opt/pets-api
    links:
      - db:mongodb
    container_name: petsapi_web_1
  db:
    image: mongo:3.0.2
    container_name: petsapi_db_1
